# Generated by Django 5.0.1 on 2024-01-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
